import type { NextPage } from 'next'
import Head from 'next/head'
import Globe from 'components/ui/Globe'
import MarqueeSlider from 'components/ui/MarqueeSlider'
import React from 'react'
// import styles from "styles/Home.module.css"

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Globe />
			<div className="flex flex-col justify-start w-full gap-8 pt-8 h-80">
				<h1 className="px-10 text-5xl font-bold leading-normal tracking-wide text-center uppercase md:text-8xl sm:text-7xl">
					Hi, I am{' '}
					<a
						href="https://github.com/irg1008"
						target="_blank"
						rel="noreferrer noopener"
						className="font-light underline transition-all bg-red-700 shadow-white hover:bg-slate-700 active:text-7xl"
					>
						Iván
					</a>{' '}
					and <br />
					my life went into...
				</h1>
				<MarqueeSlider />
			</div>
		</>
	)
}

export default Home
