name: CI

on:
  push:
  pull_request:

jobs:
  All:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        id: cache_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install Dependencies
        if: steps.cache_modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build
        run: npm run build

      - name: Unit Tests
        run: npm test

      - name: Run ESLint
        run: npm run lint:fix --if-present

      - name: Run Next.js Linter
        run: npm run lint --if-present

      - name: Run Prettier
        run: npm run prettier --if-present

      - name: Run Type Checking
        run: npm run type:check --if-present
