name: Lighthouse

on:
  deployment_status:

jobs:
  Lighthouse:
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'

    steps:
      - uses: actions/checkout@v2

      - name: Audit URLs using Lighthouse
        id: light_audit
        uses: treosh/lighthouse-ci-action@v8
        with:
          urls: |
            ${{ github.event.deployment_status.target_url }}
          budgetPath: ./budget.json
          uploadArtifacts: true
          temporaryPublicStorage: true

      - name: Update score badges
        id: format_score
        uses: actions/github-script@v5
        with:
          script: |
            const score = (res) =>
              res >= 90 ? '0CCE6B'  :
              res >= 50 ? 'FFA400' :
                          'FF4E42'

            const formatResult = (res) => Math.round((res * 100))

            // Results.
            const result = ${{ steps.light_audit.outputs.manifest }}[0].summary
            Object.keys(result).forEach((key) => result[key] = formatResult(result[key]))

            // Colors.
            const colors = {
              performance: score(result.performance),
              accessibility: score(result.accessibility),
              'best-practices': score(result.best_practices),
              seo: score(result.seo),
              pwa: score(result.pwa),
            }

            core.setOutput('colors', colors)
            core.setOutput('result', result);

      - run: echo "::set-output name=colors::${{ steps.format_score.outputs.colors }}"

      # ![](https://byob.yarr.is/irg1008/ivan-gazquez-art/performance)
      - name: Performance Badge
        uses: RubbaBoy/BYOB@v1.2.1
        with:
          NAME: performance
          LABEL: Performance
          STATUS: ${{ steps.format_score.outputs.result.performance }}
          COLOR: ${{ steps.format_score.outputs.colors.performance }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ![](https://byob.yarr.is/irg1008/ivan-gazquez-art/accessibility)
      - name: Accessibility Badge
        uses: RubbaBoy/BYOB@v1.2.1
        with:
          NAME: accessibility
          LABEL: Accessibility
          STATUS: ${{ steps.format_score.outputs.result.accessibility }}
          COLOR: ${{ steps.format_score.outputs.colors.accessibility }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ![](https://byob.yarr.is/irg1008/ivan-gazquez-art/best-practices)
      - name: Best Practices Badge
        uses: RubbaBoy/BYOB@v1.2.1
        with:
          NAME: best-practices
          LABEL: Best Practices
          STATUS: ${{ steps.format_score.outputs.result['best-practices'] }}
          COLOR: ${{ steps.format_score.outputs.colors['best-practices'] }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ![](https://byob.yarr.is/irg1008/ivan-gazquez-art/seo)
      - name: SEO Badge
        uses: RubbaBoy/BYOB@v1.2.1
        with:
          NAME: seo
          LABEL: SEO
          STATUS: ${{ steps.format_score.outputs.result.seo }}
          COLOR: ${{ steps.format_score.outputs.colors.seo }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ![](https://byob.yarr.is/irg1008/ivan-gazquez-art/pwa)
      - name: PWA Badge
        uses: RubbaBoy/BYOB@v1.2.1
        with:
          NAME: pwa
          LABEL: Progressive Web App
          STATUS: ${{ steps.format_score.outputs.result.pwa }}
          COLOR: ${{ steps.format_score.outputs.colors.pwa }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
