name: Lighthouse

on:
  deployment_status:

jobs:
  Lighthouse:
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'

    steps:
      - uses: actions/checkout@v2

      - name: Audit URLs using Lighthouse
        id: light_audit
        uses: treosh/lighthouse-ci-action@v8
        with:
          urls: |
            ${{ github.event.deployment_status.target_url }}
          budgetPath: ./budget.json
          uploadArtifacts: true
          temporaryPublicStorage: true

      - name: Update score badges
        id: format_score
        uses: actions/github-script@v5
        with:
          script: |
            const score = (res) =>
              res >= 90 ? '#0CCE6B'  :
              res >= 50 ? '#FFA400' :
                          '#FF4E42'

            const formatResult = (res) => Math.round((res * 100))

            // Results.
            const result = ${{ steps.light_audit.outputs.manifest }}[0].summary
            Object.keys(result).forEach((key) => result[key] = formatResult(result[key]))



            // Colors.
            const colors = {
              performance: score(result.performance),
              accessibility: score(result.accessibility),
              'best-practices': score(result['best-practices']),
              seo: score(result.seo),
              pwa: score(result.pwa),
            }

            core.setOutput('colors', colors)
            core.setOutput('result', result)

      - run: echo "${{ steps.format_score.outputs.result }}"

      # ![](https://byob.yarr.is/irg1008/ivan-gazquez-art/performance)
      - name: Performance Badge
        uses: schneegans/dynamic-badges-action@v1.1.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: d2b8264480d6297099513f845326e18c
          filename: test.json
          label: Performance
          message: ${{ steps.format_score.outputs.result.performance }}
          color: ${{ steps.format_score.outputs.colors.performance }}

      # ![](https://byob.yarr.is/irg1008/ivan-gazquez-art/accessibility)
      - name: Accessibility Badge
        uses: schneegans/dynamic-badges-action@v1.1.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: ea115f2dc9b462b4526f3b30867afea2
          filename: test.json
          label: Accessibility
          message: ${{ steps.format_score.outputs.result.accessibility }}
          color: ${{ steps.format_score.outputs.colors.accessibility }}

      # ![](https://byob.yarr.is/irg1008/ivan-gazquez-art/best-practices)
      - name: Best Practices Badge
        uses: schneegans/dynamic-badges-action@v1.1.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: 2f6773cce32e149f19e6131c0df056ee
          filename: test.json
          label: Best Practices
          message: ${{ steps.format_score.outputs.result['best-practices'] }}
          color: ${{ steps.format_score.outputs.colors['best-practices'] }}

      # ![](https://byob.yarr.is/irg1008/ivan-gazquez-art/seo)
      - name: SEO Badge
        uses: schneegans/dynamic-badges-action@v1.1.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: c9fae7fcded25e6227f9f5b0a7086819
          filename: test.json
          label: SEO
          message: ${{ steps.format_score.outputs.result.seo }}
          color: ${{ steps.format_score.outputs.colors.seo }}

      # ![](https://byob.yarr.is/irg1008/ivan-gazquez-art/pwa)
      - name: PWA Badge
        uses: schneegans/dynamic-badges-action@v1.1.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: b3532629ba36bb272895d5c2b2db2103
          filename: test.json
          label: PWA
          message: ${{ steps.format_score.outputs.result.pwa }}
          color: ${{ steps.format_score.outputs.colors.pwa }}
