name: Lighthouse

on:
  deployment_status:

jobs:
  Lighthouse:
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'

    steps:
      - uses: actions/checkout@v2

      - name: Audit URLs using Lighthouse
        id: light_audit
        uses: treosh/lighthouse-ci-action@v8
        with:
          urls: |
            ${{ github.event.deployment_status.target_url }}
          budgetPath: ./budget.json
          uploadArtifacts: true
          temporaryPublicStorage: true

      - name: Update score badges
        id: format_score
        uses: actions/github-script@v5
        with:
          script: |
            const score = (res) =>
              res >= 90 ? '0CCE6B'  :
              res >= 50 ? 'FFA400' :
                          'FF4E42'

            const formatResult = (res) => Math.round((res * 100))

            // Results.
            const result = ${{ steps.light_audit.outputs.manifest }}[0].summary
            Object.keys(result).forEach((key) => result[key] = formatResult(result[key]))

            // Colors.
            const color = {
              performance: score(result.performance),
              accessibility: score(result.accessibility),
              'best-practices': score(result['best-practices']),
              seo: score(result.seo),
              pwa: score(result.pwa),
            }

            core.setOutput('colors', color)

      - run: echo "Performance color ${{ steps.format_score.outputs.colors.performance }}"

      - name: Accessibility Badge
        uses: RubbaBoy/BYOB@v1.2.1
        with:
          NAME: accessibility
          LABEL: Accessibility
          STATUS: ${{ steps.format_score.outputs.results.accessibility }}
          COLOR: ${{ steps.format_score.outputs.colors.accessibility }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: echo "Performance color ${{ steps.format_score.outputs.colors.performance }}"

      - name: Best Practices Badge
        uses: RubbaBoy/BYOB@v1.2.1
        with:
          NAME: best-practices
          LABEL: Best Practices
          STATUS: "${{ steps.format_score.outputs.results['best-practices'] }}"
          COLOR: "${{ steps.format_score.outputs.colors['best-practices'] }}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: SEO Badge
        uses: RubbaBoy/BYOB@v1.2.1
        with:
          NAME: seo
          LABEL: SEO
          STATUS: ${{ steps.format_score.outputs.results.seo }}
          COLOR: ${{ steps.format_score.outputs.colors.seo }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
