name: Lighthouse

on:
  deployment_status:

jobs:
  Lighthouse:
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'

    steps:
      - uses: actions/checkout@v2

      - name: Audit URLs using Lighthouse
        id: light_audit
        uses: treosh/lighthouse-ci-action@v8
        with:
          urls: |
            ${{ github.event.deployment_status.target_url }}
          budgetPath: ./budget.json
          uploadArtifacts: true
          temporaryPublicStorage: true

      - name: Update score badges
        id: format_score
        uses: actions/github-script@v5
        with:
          script: |
            const score = (res) =>
              res >= 90 ? '0CCE6B'  :
              res >= 50 ? 'FFA400' :
                          'FF4E42'

            const formatResult = (res) => Math.round((res * 100))

            // Results.
            const data = ${{ steps.light_audit.outputs.manifest }}[0].summary
            Object.keys(data).forEach((key) => data[key] = formatResult(data[key]))

            // Colors.
            const color = {
              performance: score(data.performance),
              accessibility: score(data.accessibility),
              'best-practices': score(data['best-practices']),
              seo: score(data.seo),
              pwa: score(data.pwa),
            }

            const result = {
              color,
              data,
            }

            core.setOutput('result', JSON.stringify(result))

      - name: Performance Badge
        uses: RubbaBoy/BYOB@v1.2.1
        with:
          NAME: performance
          LABEL: Performance
          STATUS: ${{ parseJSON(steps.format_score.outputs.result).data.performance }}
          COLOR: ${{ parseJSON(steps.format_score.outputs.result).color.performance }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: echo '${{ steps.format_score.outputs.result }}'

      - name: Accessibility Badge
        uses: RubbaBoy/BYOB@v1.2.1
        with:
          NAME: accessibility
          LABEL: Accessibility
          STATUS: ${{ parseJSON(steps.format_score.outputs.result).data.accessibility }}
          COLOR: ${{ parseJSON(steps.format_score.outputs.result).color.accessibility }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Best Practices Badge
        uses: RubbaBoy/BYOB@v1.2.1
        with:
          NAME: best-practices
          LABEL: Best Practices
          STATUS: "${{ parseJSON(steps.format_score.outputs.result).data['best-practices'] }}"
          COLOR: "${{ parseJSON(steps.format_score.outputs.result).color['best-practices'] }}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: SEO Badge
        uses: RubbaBoy/BYOB@v1.2.1
        with:
          NAME: seo
          LABEL: SEO
          STATUS: ${{ parseJSON(steps.format_score.outputs.result).data.seo }}
          COLOR: ${{ parseJSON(steps.format_score.outputs.result).color.seo }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
