name: Lighthouse

on:
  deployment_status:

jobs:
  Lighthouse:
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'

    steps:
      - uses: actions/checkout@v2

      - name: Audit URLs using Lighthouse
        id: light_audit
        uses: treosh/lighthouse-ci-action@v8
        with:
          urls: |
            ${{ github.event.deployment_status.target_url }}
          budgetPath: ./budget.json
          uploadArtifacts: true
          temporaryPublicStorage: true

      - name: Format Score
        id: format_score
        uses: actions/github-script@v5
        with:
          script: |
            const result = ${{ steps.light_audit.outputs.manifest }}[0].summary

            const score = res =>
              res >= 90 ? '🟢' :
              res >= 50 ? '🟠' :
                          '🔴'
                          
            const comment = `
              ⚡️ [Lighthouse report]:
              | Category | Score |
              | --- | --- |
              | ${score(result.performance)} Performance | ${result.performance} |
              | ${score(result.accessibility)} Accessibility | ${result.accessibility} |
              | ${score(result['best-practices'])} Best practices | ${result['best-practices']} |
              | ${score(result.seo)} SEO | ${result.seo} |
              | ${score(result.pwa)} PWA | ${result.pwa} |
            `

            core.setOutput("comment", comment);
